RADGRAPH_DIR = '/dataNAS/people/jmz/data/radgraph/1.0.0'
RADSPRL_DIR = ''
STANZA_NER_DIR = ''
MIMIC_PROTOCOLING_DIR = '/dataNAS/people/jmz/data/mimic_autoprocedure_selection/'
ANOMALY_DETECTION_DIR = ''
VILMEDIC_DIR = ''
STANFORD_BODYCT_PROTOCOL_DIR = '/dataNAS/people/jmz/data/autoprotocol/cache/'
TRANSFORMERS_DOWNLOAD_PATH = '/dataNAS/people/jmz/models/transformers_downloads/'