RADGRAPH_DIR = '/DEIDPATH/data/radgraph/1.0.0'
RADSPRL_DIR = '/DEIDPATH/data/radsprl/'
STANZA_DIR = '/DEIDPATH/data/radiology_NER/Radiology-NER/'
MIMIC_PROTOCOLING_DIR = '/DEIDPATH/data/mimic_autoprocedure_selection/'
TRANSFORMERS_DOWNLOAD_PATH = '/DEIDPATH/models/transformers_downloads/'