includes:
  - config/RRS/biomed-roberta-baseline-mimic.yml

dataset:
  proto: Seq2Seq
  src:
    root: data/RRS/indiana/
    file: findings.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 128
    processing: r2gen_clean_report
  tgt:
    root: data/RRS/indiana/
    file: impression.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 75
    processing: r2gen_clean_report
