name: multimodal_biorobert_mimic
ckpt_dir: ckpt
dataset:
  proto: ImSeq2Seq
  src:
    root: data/RRS/mimic-cxr/
    file: findings.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 120
  tgt:
    root: data/RRS/mimic-cxr/
    file: impression.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 80
    processing: r2gen_clean_report
  image:
    root: data/RRS/mimic-cxr/
    file: image.tok
    image_path: data/RRS/
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg


model:
  proto: SumHugMulti
  encoder:
    proto: allenai/biomed_roberta_base
  decoder:
    proto: allenai/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664
    freeze: False



trainor:
  batch_size: 8
  optimizer: RAdam
  optim_params:
    lr: 0.00005
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGE2

validator:
  batch_size: 16
  beam_width: 8
  metrics: [ ROUGEL, ROUGE2, BLEU, METEOR, chexbert ]
  splits: [ validate ]


ensemblor:
  batch_size: 16
  beam_width: 8
  metrics: [ ROUGEL, ROUGE2, BLEU, METEOR, chexbert ]
  splits: [ validate, test ]
  mode: all
