name: convirt
ckpt_dir: ckpt

dataset:
  proto: ImSeq
  image:
    root: data/RRS/mimic-cxr/
    file: image.tok
    image_path: data/images/mimic-cxr-images-512/files/
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg
  seq:
    root: data/RRS/mimic-cxr/
    file: findings.tok
    tokenizer: data/RRS/huggingface/biomed_roberta_base
    tokenizer_max_len: 128

model:
  proto: ConVIRT
  encoder:
    proto: data/RRS/huggingface/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: avgpool
    dropout_out: 0.0
    permute: batch_first
    freeze: False

  projection:
    visual_embedding_dim: 1664
    textual_embedding_dim: 768
    projection_dim: 768

  loss:
    proto: InfoNCELoss
    tau: 1.0

trainor:
  optimizer: RAdam
  optim_params:
    lr: 0.00005
  batch_size: 64
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: loss

validator:
  batch_size: 16
  beam_width: 8
  splits: [validate]


ensemblor:
  batch_size: 16
  beam_width: 8
  splits: [validate, test]
  mode: all
