name: myvqa
ckpt_dir: ckpt

dataset:
  proto: ImLabel
  label:
    root: data/2021-VQA
    file: a.txt

  image:
    root: data/2021-VQA
    image_path: data/2021-VQA/images
    file: ids.txt
    load_memory: False
    resize: (232, 232)
    ext: .jpg

model:
  proto: VQA
  visual:
    proto: CNN
    backbone: densenet169
    output_layer: classifier
    dropout_out: 0.0
    permute: no_permute
    freeze: False

  classif:
    input_size: 1664
    num_classes: 330

  loss:
      proto: LabelSmoothingCrossEntropy
#      proto: MixUpLoss
#      criterion: LabelSmoothingCrossEntropy
#      classes: 332


trainor:
#  optimizer: sgd
  optimizer: Adam
  optim_params: {lr: 1e-3, weight_decay: 5e-4}
#  momentum: 0.9
  batch_size: 32
  lr_decay_factor: 0.5
  lr_decay_patience: 2
  lr_min: 0.000001
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: accuracy

validator:
  batch_size: 16
  metrics: [accuracy]
  splits: [val]

ensemblor:
  batch_size: 16
  metrics: [accuracy]
  splits: [val]
  mode: all # best,all