name: vae
ckpt_dir: ckpt

dataset:
  proto: ImageDataset
  root: data/SELFSUP/mimic-cxr/
  file: image.tok
  image_path: data/images/
  load_memory: False
  custom_transform_train: >
    transforms.Compose([
                    transforms.Resize(256),
                    transforms.CenterCrop(256),
                    transforms.ToTensor()])
  custom_transform_validate: >
    transforms.Compose([
                    transforms.Resize(256),
                    transforms.CenterCrop(256),
                    transforms.ToTensor()])
  ext: .jpg

model:
  proto: VAE
  image_size: 256
  num_layers: 3
  num_tokens: 8192
  codebook_dim: 1024
  hidden_dim: 128
  num_resnet_blocks: 1
  temperature: 0.9
  straight_through: False

trainor:
  optimizer: Adam
  optim_params: {lr: 1e-3}
  batch_size: 32
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 5
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 500
  early_stop: 40
  eval_start: 0
  early_stop_metric: validation_loss

validator:
  batch_size: 16
  metrics: []
  splits: [validate]


ensemblor:
  batch_size: 16
  metrics: []
  splits: [validate]
  mode: all # best,all