name: convirt_mimic
ckpt_dir: ckpt

dataset:
  proto: ImSeq
  image:
    root: data/SELFSUP/mimic-cxr/
    file: image.tok
    image_path: data/images/
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg
  seq:
    root: data/SELFSUP/mimic-cxr/
    tokenizer: allenai/biomed_roberta_base
    file: report.tok
    tokenizer_max_len: 128
    processing: r2gen_clean_report

model:
  proto: ConVIRT
  forward_batch_size: 4
  encoder:
    proto: allenai/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: resnet50
    output_layer: avgpool
    dropout_out: 0.0
    permute: batch_first
    freeze: False
  projection:
    visual_embedding_dim: 2048
    textual_embedding_dim: 768
    projection_dim: 768
  loss:
    proto: ConVIRTLoss
    tau: 0.1
    lambda_: 0.75

trainor:
  optimizer: RAdam
  optim_params:
    lr: 5e-5
  batch_size: 32
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 5
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  eval_start: 0
  early_stop: 20
  early_stop_metric: validation_loss

validator:
  batch_size: 32
  splits: [validate]

ensemblor:
  batch_size: 32
  splits: [train, validate, test]
  post_processing:
    - plot_representation:
        keys:
          - linguistic
          - visual
        labels_keep: [Pleural Effusion,Pneumonia,Pneumothorax,Cardiomegaly,Atelectasis]
        max_samples_per_class: 250
  mode: best-1
