includes:
  - config/SELFSUP/convirt-mimic.yml

name: convirt_indiana
dataset:
  image:
    root: data/SELFSUP/indiana
    file: image.tok
    image_path: data/images/
    ext: .png
  seq:
    root: data/SELFSUP/indiana
    file: report.tok
    tokenizer_max_len: 150
    processing: r2gen_clean_report

trainor:
  clip_grad_norm: 0.75
  lr_decay_params:
    factor: 0.8
    patience: 5
  optim_params:
    lr: 5e-05

ensemblor:
  post_processing: null