includes:
  - config/SELFSUP/convirt-mimic.yml
name: convirt_padchest

dataset:
  image:
    root: data/SELFSUP/padchest/all
    file: image.tok
    image_path: data/images/padchest-images-512/
    ext: .png
  seq:
    root: data/SELFSUP/padchest/all/
    tokenizer: null
    file: report.tok
    tokenizer_max_len: 60
    processing: gloria_clean_report_chexpert

model:
  forward_batch_size: 4
  encoder:
    proto: null
    add_pooling_layer: True

    attention_probs_dropout_prob: 0.1
    bos_token_id: 0
    eos_token_id: 2
    gradient_checkpointing: false
    hidden_act: gelu
    hidden_dropout_prob: 0.1
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 3072
    layer_norm_eps: 1e-05
    max_position_embeddings: 514
    num_attention_heads: 12
    num_hidden_layers: 12
    pad_token_id: 1
    position_embedding_type: absolute
    transformers_version: 4.5.1
    type_vocab_size: 1
    use_cache: true
    vocab_size: 6106


trainor:
  clip_grad_norm: 0.25,
  lr_decay_params:
    factor: 0.8
    patience: 5
  optim_params:
    lr: 1e-05

ensemblor:
  post_processing: null
