dataset:
  proto: ImSeq
  image:
    root: data/SELFSUP/mimic-cxr/
    file: image.tok
    image_path: data/images/
    resize: 256
    crop: 224
    ext: .jpg
    load_memory: False

  seq:
    root: data/SELFSUP/mimic-cxr/
    tokenizer: emilyalsentzer/Bio_ClinicalBERT
    file: report.tok
    tokenizer_max_len: 128
    processing: r2gen_clean_report

model:
  proto: GLoRIA
  forward_batch_size: 12
  encoder:
    proto: emilyalsentzer/Bio_ClinicalBERT
    last_n_layers: 4

  cnn:
    proto: CNN
    backbone: resnet50
    output_layer: avgpool
    dropout_out: 0.0
    permute: batch_first
    freeze: False

  visual_embedder:
    interm_feature_dim: 1024
    feature_dim: 2048

  loss:
    local_loss_weight: 1.0
    global_loss_weight: 1.0
    temp1: 4.0
    temp2: 5.0
    temp3: 10.0

trainor:
  optimizer: Adam
  optim_params:
    lr: 0.0001
  batch_size: 48
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 5
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  early_stop: 20
  eval_start: 0
  early_stop_metric: validation_loss

validator:
  batch_size: 48
  splits: [validate]

ensemblor:
  batch_size: 48
  splits: [train, validate, test]
  post_processing:
    - plot_representation:
        keys:
          - linguistic
          - visual
        labels_keep: [Pleural Effusion,Pneumonia,Pneumothorax,Cardiomegaly,Atelectasis]
        max_samples_per_class: 250
  mode: best-1
