name: swav
ckpt_dir: ckpt

dataset:
  proto: IndexDataset
  dataset: ImageDataset
  root: data/SELFSUP/mimic-cxr/
  file: image.tok
  image_path: data/images/
  custom_transform_train: >
    lambda x : torch.cat([transforms.Compose([
                                    transforms.Resize(256),
                                    transforms.RandomCrop(224),
                                    transforms.RandomHorizontalFlip(),
                                    transforms.ToTensor(),
                                    transforms.Normalize((0.485, 0.456, 0.406),
                                                         (0.229, 0.224, 0.225)),
                                    ])(x),
                transforms.Compose([
                                    transforms.Resize(256),
                                    transforms.RandomCrop(224),
                                    transforms.RandomHorizontalFlip(),
                                    transforms.ToTensor(),
                                    transforms.Normalize((0.485, 0.456, 0.406),
                                                         (0.229, 0.224, 0.225)),
                                    ])(x)])
  custom_transform_validate: >
    transforms.Compose([
                    transforms.Resize((224, 224)),
                    transforms.ToTensor(),
                    transforms.Normalize((0.485, 0.456, 0.406),
                                         (0.229, 0.224, 0.225))])

  load_memory: False
  ext: .jpg

model:
  proto: PCL
  clustering_epoch_start: 21
  config:
    arch: resnet50
    low_dim: 768
    pcl_r: 1536
    moco_m: 0.999
    temperature: 0.2
    mlp: true
#    num_cluster: [2000,4000,8000]
    num_cluster: [2250,4500,9000]

trainor:
  optimizer: RAdam
  optim_params:
    lr: 0.001
  batch_size: 32
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 5
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
    decay_on_training_loss: true
  decay_metric_start: 21
  early_stop_start: 21
  epochs: 200
  early_stop: 200
  eval_start: 20
  early_stop_metric: training_loss
  drop_last: true

validator:
  batch_size: 32
  splits: [train_as_validate]

ensemblor:
  batch_size: 32
  splits: [train, validate, test]
  mode: best-1
