name: swav
ckpt_dir: ckpt

dataset:
  proto: ImageDataset
  root: data/SELFSUP/mimic-cxr/
  file: image.tok
  image_path: data/images/
  custom_transform_train: 'SwAVTrainDataTransform(
                            normalize=transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
                            size_crops=[224, 96],
                            nmb_crops=[2, 6],
                            min_scale_crops=[0.14, 0.05],
                            max_scale_crops=[1.0, 0.14],
                            gaussian_blur=True,
                            jitter_strength=1.0)'
  custom_transform_validate: 'SwAVEvalDataTransform(
                            normalize=transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
                            size_crops=[224, 96],
                            nmb_crops=[2, 6],
                            min_scale_crops=[0.14, 0.05],
                            max_scale_crops=[1.0, 0.14],
                            gaussian_blur=True,
                            jitter_strength=1.0)'

#SwAVFinetuneTransform(input_height=224, eval_transform=True)
  ext: .jpg

model:
  proto: SwaV
  config:
    arch: resnet50
    nmb_prototypes: 60
    hidden_mlp: 2048
    output_dim: 768
    first_conv: True
    maxpool1: True
    temperature: 0.1
    epsilon: 0.05
    nmb_crops: [2, 6]
    crops_for_assign: [0, 1]
    sinkhorn_iterations: 3
    queue_length: 0

trainor:
  optimizer: RAdam
  optim_params:
    lr: 0.001
  batch_size: 16
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 5
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 999
  early_stop: 20
  eval_start: 0
  early_stop_metric: validation_loss

validator:
  batch_size: 16
  splits: [validate]

ensemblor:
  batch_size: 16
  splits: [train, validate, test]
  mode: best-1
