name: rcnn
ckpt_dir: ckpt

dataset:
  proto: RCNNDataset
  image:
    root: data/RCNN/VinBigData/
    file: image.tok
    image_path: data/images/
    load_memory: False
    ext: .png
    custom_transform_train: >
      transforms.Compose([
                      transforms.ToTensor()])
    custom_transform_validate: >
      transforms.Compose([
                      transforms.ToTensor()])

  label:
    root: data/RCNN/VinBigData/
    file: label.tok

  bbox:
    root: data/RCNN/VinBigData/
    file: bbox.tok

model:
  proto: RCNN

trainor:
  optimizer: RAdam
  optim_params: {lr: 3e-4}
  batch_size: 5
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 0
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: validation_loss

validator:
  batch_size: 8
  metrics: []
  splits: [validate]


ensemblor:
  generate_images: True
  num_images: 5
  batch_size: 2
  metrics: []
  splits: [validate]
  mode: all # best,all