name: multimodal_biorobert_mimic
ckpt_dir: ckpt
dataset:
  proto: ImageTextDataset
  root: data/report_sum/mimic-cxr/
  src: findings.tok
  tgt: impression.tok
  tokenizer: data/report_sum/huggingface/biomed_roberta_base
  max_len: 80
  images: image.tok
  load_memory: False
  image_path: data/report_sum/

model:
  proto: VisualSeq2SeqHug
  encoder:
    proto: data/report_sum/huggingface/biomed_roberta_base
  decoder:
    proto: data/report_sum/huggingface/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664

trainor:
  lr: 0.00005
  weight_decay: 0.00001 #1e-05
  batch_size: 64
  lr_decay_factor: 0.5
  lr_decay_patience: 2
  lr_min: 0.000001
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGE2

validator:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR]
  splits: [validate]


ensemblor:
  proto: Ensemblor
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR]
  #  splits: [indiana_dev]
  splits: [validate, test]
  mode: all # best,all
