eval_name: bertbase_procedure
model_name_or_path: bert-base-uncased
tokenizer_path: bert-base-uncased
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'