eval_name: radbert1_stanza
model_name_or_path: StanfordAIMI/RadBERT
tokenizer_path: StanfordAIMI/RadBERT
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'