eval_name: electrabase_procedure
model_name_or_path: google/electra-base-discriminator
tokenizer_path: google/electra-base-discriminator
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'