eval_name: robertabase_procedure
model_name_or_path: roberta-base
tokenizer_path: roberta-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'