eval_name: debertav3large_stanza
model_name_or_path: microsoft/deberta-v3-large
tokenizer_path: microsoft/deberta-v3-large
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'