eval_name: biolinkbertlarge
model_name_or_path: michiyasunaga/BioLinkBERT-large
tokenizer_path: michiyasunaga/BioLinkBERT-large
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True