eval_name: gatortron
model_name_or_path: /PATH_TO//models/gatortron_v1/huggingface/
tokenizer_path: /PATH_TO//models/gatortron_v1/huggingface/tokenizer
config_name: /PATH_TO//models/gatortron_v1/huggingface/config.json
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'