eval_name: debertav3base_procedure
model_name_or_path: microsoft/deberta-v3-base
tokenizer_path: microsoft/deberta-v3-base
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'