eval_name: radbert1
model_name_or_path: StanfordAIMI/RadBERT
tokenizer_path: StanfordAIMI/RadBERT
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True