eval_name: radbert2
model_name_or_path: zzxslp/RadBERT-RoBERTa-4m
tokenizer_path: zzxslp/RadBERT-RoBERTa-4m
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True