eval_name: debertav3base
model_name_or_path: microsoft/deberta-v3-base
tokenizer_path: microsoft/deberta-v3-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'