eval_name: debertav3base
model_name_or_path: microsoft/deberta-v3-base
tokenizer_path: microsoft/deberta-v3-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True