eval_name: electrabase_stanza
model_name_or_path: google/electra-base-discriminator
tokenizer_path: google/electra-base-discriminator
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'