eval_name: robertalarge
model_name_or_path: roberta-large
tokenizer_path: roberta-large
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'