eval_name: biolinkbert-large
model_name_or_path: michiyasunaga/BioLinkBERT-large
tokenizer_path: michiyasunaga/BioLinkBERT-large
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'