eval_name: electralarge
model_name_or_path: google/electra-large-discriminator
tokenizer_path: google/electra-large-discriminator
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'