eval_name: robertalarge_stanza
model_name_or_path: roberta-large
tokenizer_path: roberta-large
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'