eval_name: debertav3large
model_name_or_path: microsoft/deberta-v3-large
tokenizer_path: microsoft/deberta-v3-large
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True