eval_name: gatortron
model_name_or_path: /PATH_TO//models/gatortron_v1/huggingface/
tokenizer_path: /PATH_TO//models/gatortron_v1/huggingface/tokenizer
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'