eval_name: robertabase
model_name_or_path: roberta-base
tokenizer_path: roberta-base
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'