eval_name: robertabase
model_name_or_path: roberta-base
tokenizer_path: roberta-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True