eval_name: pubmedbert
model_name_or_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
tokenizer_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True