eval_name: bertlarge_stanza
model_name_or_path: bert-large-uncased
tokenizer_path: bert-large-uncased
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'