eval_name: bioclinicalbert
model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
tokenizer_path: emilyalsentzer/Bio_ClinicalBERT
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'