eval_name: electrasmall_stanza
model_name_or_path: google/electra-small-discriminator
tokenizer_path: google/electra-small-discriminator
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'