eval_name: deberta-v3-large
model_name_or_path: microsoft/deberta-v3-large
tokenizer_path: microsoft/deberta-v3-large
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'