eval_name: bioclinicalbert
model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
tokenizer_path: emilyalsentzer/Bio_ClinicalBERT
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True