eval_name: debertav3base_stanza
model_name_or_path: microsoft/deberta-v3-base
tokenizer_path: microsoft/deberta-v3-base
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'