eval_name: gatortron_stanza
model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
tokenizer_path: emilyalsentzer/Bio_ClinicalBERT
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'