eval_name: debertav3base_procedure
model_name_or_path: microsoft/deberta-v3-base
tokenizer_path: microsoft/deberta-v3-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'