eval_name: biom-electra
model_name_or_path: sultan/BioM-ELECTRA-Large-Discriminator
tokenizer_path: sultan/BioM-ELECTRA-Large-Discriminator
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'