eval_name: radbert1_stanza
model_name_or_path: StanfordAIMI/RadBERT
tokenizer_path: StanfordAIMI/RadBERT
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'