eval_name: roberta_large
model_name_or_path: roberta-large
tokenizer_path: roberta-large
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['radgraph_ner']
output_dir: '../results/ner/'