eval_name: electrasmall
model_name_or_path: google/electra-small-discriminator
tokenizer_path: google/electra-small-discriminator
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'