eval_name: robertalarge_procedure
model_name_or_path: roberta-large
tokenizer_path: roberta-large
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'