eval_name: radbert2_pretrained
model_name_or_path: /dataNAS/people/jmz/jmz_code/radiology_nlp/rales/results/classification/_radbert_ucsd_mimiciii_ct_procedure/run-9/checkpoint-1362
tokenizer_path: /dataNAS/people/jmz/jmz_code/radiology_nlp/rales/results/classification/_radbert_ucsd_mimiciii_ct_procedure/run-9/checkpoint-1362
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanford_body_ct_protocol_25']
output_dir: '../results/classification/'