eval_name: bioclinicalbert
model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
tokenizer_path: emilyalsentzer/Bio_ClinicalBERT
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanford_body_ct_protocol_25']
output_dir: '../results/classification/'