eval_name: gatortron
model_name_or_path: /DEIDPATH/models/gatortron_v1/huggingface/
tokenizer_path: /DEIDPATH/models/gatortron_v1/huggingface/tokenizer
config_name: /DEIDPATH/models/gatortron_v1/huggingface/config.json
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'