eval_name: biolinkbertbase_procedure
model_name_or_path: michiyasunaga/BioLinkBERT-base
tokenizer_path: michiyasunaga/BioLinkBERT-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'