eval_name: bertbase_procedure
model_name_or_path: bert-base-uncased
tokenizer_path: bert-base-uncased
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'