eval_name: bertlarge
model_name_or_path: bert-large-uncased
tokenizer_path: bert-large-uncased
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'