eval_name: biolinkbertlarge_stanza
model_name_or_path: michiyasunaga/BioLinkBERT-large
tokenizer_path: michiyasunaga/BioLinkBERT-large
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'