eval_name: biolinkbertbase_stanza
model_name_or_path: michiyasunaga/BioLinkBERT-base
tokenizer_path: michiyasunaga/BioLinkBERT-base
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'