eval_name: radbert_ucsd
model_name_or_path: zzxslp/RadBERT-RoBERTa-4m
tokenizer_path: zzxslp/RadBERT-RoBERTa-4m
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'