eval_name: pubmedbert_base
model_name_or_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
tokenizer_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'