eval_name: biolinkbertbase_procedureeff
model_name_or_path: michiyasunaga/BioLinkBERT-base
tokenizer_path: michiyasunaga/BioLinkBERT-base
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure_10pct','mimiciii_ct_procedure_1pct']
output_dir: '../results/classification/'