eval_name: biolinkbert_base
model_name_or_path: michiyasunaga/BioLinkBERT-base
tokenizer_path: michiyasunaga/BioLinkBERT-base
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanford_body_ct_protocol']
output_dir: '../results/classification/'