eval_name: gatortron
model_name_or_path: /PATH_TO//models/gatortron_v1/huggingface/
tokenizer_path: /PATH_TO//models/gatortron_v1/huggingface/tokenizer
config_name: /PATH_TO//models/gatortron_v1/huggingface/config.json
cache_dir: /PATH_TO//models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True