eval_name: electrasmall
model_name_or_path: google/electra-small-discriminator
tokenizer_path: google/electra-small-discriminator
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner','mimiciii_ct_procedure']
output_dir: '../results/lp/'
linear_probe: True