eval_name: robertabase_stanza
model_name_or_path: roberta-base
tokenizer_path: roberta-base
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'