eval_name: roberta_large
model_name_or_path: roberta-large
tokenizer_path: roberta-large
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'