eval_name: biolinkbertlarge_stanza
model_name_or_path: michiyasunaga/BioLinkBERT-large
tokenizer_path: michiyasunaga/BioLinkBERT-large
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['stanza_ner_10pct', 'stanza_ner_1pct']
output_dir: '../results/ner/'