eval_name: electralarge_procedure
model_name_or_path: google/electra-large-discriminator
tokenizer_path: google/electra-large-discriminator
cache_dir: /dataNAS/people/jmz/models/transformers_downloads/
eval_datasets: ['mimiciii_ct_procedure']
output_dir: '../results/classification/'