eval_name: radbert2_stanza
model_name_or_path: zzxslp/RadBERT-RoBERTa-4m
tokenizer_path: zzxslp/RadBERT-RoBERTa-4m
cache_dir: /DEIDPATH/models/transformers_downloads/
eval_datasets: ['stanza_ner']
output_dir: '../results/ner/'