name: multimodal_biorobert_mimic
ckpt_dir: ckpt
dataset:
  proto: ImSeq2Seq
  src:
    root: data/report_sum/mimic-cxr/
    file: findings.tok
    tokenizer: data/report_sum/huggingface/biomed_roberta_base
    max_len: 80
  tgt:
    root: data/report_sum/mimic-cxr/
    file: impression.tok
    tokenizer: data/report_sum/huggingface/biomed_roberta_base
    max_len: 80
  image:
    root: data/report_sum/mimic-cxr/
    file: image.tok
    image_path: data/report_sum/
    load_memory: False
    resize: 256
    ext: .jpg


model:
  proto: SumHugMulti
  encoder:
    proto: data/report_sum/huggingface/biomed_roberta_base
  decoder:
    proto: data/report_sum/huggingface/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664

trainor:
  optimizer: Adam
  optim_params: {lr: 0.00005, weight_decay: 0.00001}
  batch_size: 64
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGE2

validator:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR, ROUGEL]
  splits: [validate]


ensemblor:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR, ROUGEL]
  splits: [validate, test]
  mode: all
