name: mysiim_tr
ckpt_dir: ckpt

dataset:
  proto: ImLabel
  label:
    root: data/siim
    file: a.txt

  image:
    root: data/siim
    image_path: data/siim/images
    file: ids.txt
    load_memory: False
    resize: (256, 256)
    ext: .dcm


model:
  proto: VQA_tr
  visual:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    freeze: False

  adapter:
    input_size: 1664
    output_size: 768

  transformer:
    hidden_size: 768
    intermediate_size: 2048
    num_hidden_layers: 12
    num_attention_heads: 8
    attention_probs_dropout_prob: 0.1
    hidden_dropout_prob: 0.1
    hidden_act: gelu
    initializer_range: 0.02
    layer_norm_eps: 1.e-12

  classif:
    input_size: 768
    num_classes: 4

  loss:
#      proto: LabelSmoothingCrossEntropy
      proto: CrossEntropyLoss


trainor:
  optimizer: Adam
  optim_params: {lr: 1e-4, weight_decay: 5e-4}
  batch_size: 32
  lr_decay_factor: 0.5
  lr_decay_patience: 5
  lr_min: 0.000001
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: accuracy

validator:
  batch_size: 16
  metrics: [accuracy]
  splits: [test]

ensemblor:
  batch_size: 16
  metrics: [accuracy, f1-score, auroc]
  splits: [test]
  mode: all # best,all