includes:
  - config/RRG/biomed-roberta-baseline-eeg.yml

name: rrg_mimic
ckpt_dir: ckpt
dataset:
  proto: TUHDataset
  eeg:
    root: data/RRG/TUH/
    file: impression.eeg.tok
    eeg_path: data/RRG/TUH/
    clip_len: 60
  seq:
    root: data/RRG/TUH/
    file: impression.tok
    tokenizer: null
    tokenizer_max_len: 100
    processing: ifcc_clean_report
    source: tgt

model:
  decoder:
    proto: null
    add_cross_attention: true
    attention_probs_dropout_prob: 0.1
    bos_token_id: 0
    eos_token_id: 2
    gradient_checkpointing: false
    hidden_act: gelu
    hidden_dropout_prob: 0.1
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 3072
    is_decoder: true
    layer_norm_eps: 1e-05
    max_position_embeddings: 514
    num_attention_heads: 12
    num_hidden_layers: 1
    pad_token_id: 1
    position_embedding_type: absolute
    transformers_version: 4.5.1
    type_vocab_size: 1
    use_cache: true
