includes:
  - config/RRG/biomed-roberta-baseline-mimic.yml
name: rrg_padchest
dataset:
  image:
    root: data/RRG/indiana/
    file: image.tok
    image_path: data/images/
  seq:
    root: data/RRG/indiana/
    file: impression.tok
    tokenizer: data/RRG/huggingface/biomed_roberta_base
    tokenizer_max_len: 90
    source: tgt
