name: rrg_mimic
ckpt_dir: ckpt
dataset:
  proto: ImSeq
  image:
    root: data/RRG/mimic-cxr/impression/
    file: image.tok
    image_path: data/images/
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg
  seq:
    root: data/RRG/mimic-cxr/impression/
    file: impression.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 120
    processing: r2gen_clean_report
    source: tgt

model:
  proto: RRG
  decoder:
    proto: allenai/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664
    freeze: False

trainor:
  batch_size: 128
  optimizer: RAdam
  optim_params:
    lr: 5e-5
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: chexbert-5_micro avg_f1-score

validator:
  batch_size: 4
  beam_width: 8
  metrics:
    - ROUGEL
    - BLEU
    - METEOR
    - CIDERD
    - chexbert
    - radentitymatchexact
    - radentitynli
    - radgraph
  splits: [validate]


ensemblor:
  batch_size: 4
  beam_width: 8
  metrics:
    - ROUGEL
    - BLEU
    - METEOR
    - CIDERD
    - chexbert
    - radentitymatchexact
    - radentitynli
    - radgraph
  splits: [validate, test]
  mode: best-1
