name: RRG
ckpt_dir: ckpt
dataset:
  proto: ImSeq
  image:
    root: data/RRG/r2gen/mimic-cxr/
    file: image.tok
    image_path: data/images/mimic-cxr-images-512/files/
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg
  seq:
    root: data/RRG/r2gen/mimic-cxr/
    file: impression.tok
    tokenizer: data/RRG/huggingface/biomed_roberta_base
    tokenizer_max_len: 120
    source: tgt

model:
  proto: MyModel
  linear:
    in_features: 512
    out_features: 1024
  use_relu: true

trainor:
  batch_size: 8
  optimizer: RAdam
  optim_params:
    lr: 0.00005
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGEL

validator:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGEL, BLEU, METEOR]
  splits: [validate]


ensemblor:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGEL, BLEU, METEOR]
  #  splits: [indiana_dev]
  splits: [validate, test]
  mode: all # best,all
