name: RRG
ckpt_dir: ckpt
dataset:
  proto: ImSeqDataset
  image:
    root: data/rrg/
    file: id.tok
    image_path: data/report_sum/mimic-cxr-images-512/files/
    load_memory: False
    ext: .jpg
  seq:
    root: data/rrg/
    file: a.tok
    tokenizer: data/report_sum/huggingface/biomed_roberta_base
    max_len: 100
    tokenizer_max_len: 250
    source: tgt

model:
  proto: RRG
  decoder:
    proto: data/report_sum/huggingface/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664
    freeze: True

trainor:
  batch_size: 8
  optimizer: Adam
  optim_params:
    lr: 0.00005
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 2
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGE2

validator:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR]
  splits: [validate]


ensemblor:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGE2, BLEU, METEOR]
  #  splits: [indiana_dev]
  splits: [validate, test]
  mode: all # best,all
