name: cap
ckpt_dir: ckpt

dataset:
  proto: ImSeq
  image:
    root: data/MCAP
    file: image.tok
    image_path: data/MCAP/images
    load_memory: False
    resize: 512
    crop: 300
    ext: .jpg

  seq:
    root: data/MCAP
    file: caption.tok
    tokenizer: allenai/biomed_roberta_base
    tokenizer_max_len: 50
    source: tgt
    show_length: True

model:
  proto: RRG
  decoder:
    proto: allenai/biomed_roberta_base
  cnn:
    proto: CNN
    backbone: densenet169
    output_layer: features
    dropout_out: 0.0
    permute: batch_first
    visual_embedding_dim: 1664
    freeze: False


trainor:
  batch_size: 8
  optimizer: RAdam
  optim_params:
    lr: 0.00005
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: BLEU

validator:
  batch_size: 16
  beam_width: 8
  metrics: [BLEU]
  splits: [validate]